### PR TITLE
Fix the problem that can not save assignments with empty slug field

### LINKED ISSUE #740: Saving an assignment with an empty title and/or slug
If a user saves an assignment (individual or group) with an empty title and/or an empty slug on the settings page, the site crashes.

### PR DESCRIPTION
**Pull request by dinever**
Closes #740

When the user sets an assignment with an empty slug value. The assignment will be failed to save but the object `@assignment` still carries the empty slug, which causes the page not able to be rendered. So we reload the assignment before rendering the view when user sets an empty assignment slug to avoid the problem.

### CODE REVIEW

**Comment by tarebyte** [comment]
@dinever mind adding a test so future @tarebyte doesn't break this?

**Comment by dinever** [comment]
@tarebyte Sure 😄  Working on that!

**Comment by dinever** [comment]
Hi @tarebyte, I believe this one is ready for a 👀

**Comment by tarebyte** [comment]
:metal:

**Comment by tarebyte** [comment]
fix_slug

**Pull request merged**
