### PR TITLE
Add puma_worker_killer to Classroom

### LINKED ISSUE #385: Memory quota exceeded errors on Heroku
I'm seeing occasional `R14: Memory Quota Exceeded` errors in the Heroku logs.

https://github.com/schneems/puma_worker_killer is a possible solution for those errors.

cc/ @mkcode because you know a thing or two about memory issues.

### PR DESCRIPTION
**Pull request by tarebyte**
Closes #385 

/cc @mkcode @johndbritton

### CODE REVIEW

**Comment by johndbritton** [comment]
@mkcode How do you recommend setting the configuration for this?

**Comment by mkcode** [comment]
```ruby
+PumaWorkerKiller.config do |config|
+  config.ram           = Integer(ENV['DYNO_RAM'] || 512) # mb
+  config.frequency     = 5    # seconds
+  config.percent_usage = 0.99
+  config.rolling_restart_frequency = 12 * 3600 # 12 hours in seconds
+end
+PumaWorkerKiller.start
```

 * If you use the heroku performance dynos, upping the ram size is important - otherwise the default of 512 is fine.
 * Default frequency is 10, this may be fine.
 * Default rolling_restart_frequency is 6hrs. This may be fine as well.

**Comment by tarebyte** [comment]
@mkcode @johndbritton I've updated this with the suggested config, anything else before we :shipit:?

**Comment by johndbritton** [comment]
:shipit: Thanks for the help @mkcode!

**Pull request merged**
