### PR TITLE
Foreman development

### PR DESCRIPTION
**Pull request by mkcode**
Adds instructions for using foreman in development mode, to run required executables. Misc readme improvements.

### CODE REVIEW

**Comment by johndbritton** [comment]
:cool: I'll leave this to @tarebyte in case he has any feedback.

**Comment by tarebyte** [comment]
@mkcode this looks great! Can you remove `script/sidekiq` and the reference to it in the README?

**Comment by tarebyte** [comment]
@mkcode what do you think about putting making foreman into it's own script?

```bash
#!/bin/sh

# script/workers: Run all of worker needed using foreman

set -e

cd "$(dirname "$0")/.."

foreman start -f Procfile.dev
```

**Comment by mkcode** [comment]
@tarebyte - Nice suggestions! I updated the readme and scripts to reflect your last two comments.

**Comment by mkcode** [comment]
@tarebyte - I added back `script/sidekiq` for the users that prefer to run redis and memcache system wide, so they will not be forced to comment out the items in `Procfile.dev`. Should make for happy development for all now. :tada:

**Comment by tarebyte** [comment]
Looks great, thanks @mkcode!

**Comment by johndbritton** [comment]
Thanks @mkcode, I just followed the instructions and they worked perfectly.

**Pull request merged**
