### PR TITLE
Added note stating project is open source with link to repo

### PR DESCRIPTION
**Pull request by mostlybadfly**
I thought i'd submit the PR, this is related to [issue#296 ](https://github.com/education/classroom/issues/296). I added an additional line in `shared/_footer.html.erb` to render the note requested.

### CODE REVIEW

**Comment by johndbritton** [comment]
Can you update to use the full name "Classroom for GitHub" and include a screenshot here for easy previewing?

**Comment by mostlybadfly** [comment]
S
screen shot 2015-10-02 at 12 54 25 pm
ure thing, here you go!

**Comment by tarebyte** [comment]
@mostlybadfly ~~Github~~ GitHub :smile_cat:

**Comment by tarebyte** [comment]
@mostlybadfly Also it looks like you updated your screenshot but didn't push up the commit.

**Comment by mostlybadfly** [comment]
Oh no, sorry! first actual PR, I'll get the hang of it :sweat_smile: updated.

**Comment by tarebyte** [comment]
@mostlybadfly not a problem, thank you so much for your contribution!

This looks fine to me, any other thoughts @johndbritton?

**Comment by johndbritton** [comment]
Thanks :sparkles:

**Pull request merged**
