### PR TITLE
Using Classroom should not remove owners role

### LINKED ISSUE #332: Using classroom removes owner role
Hello everyone, 

I'm trying to get GH Classroom up and running for my organization "mmbuw". I recently created a first assignment and handed out the invitation link, however, this morning, I discovered that 

a) all teams were grayed out in the classroom and deleted in the organization, and that 
b) all team repositories had been deleted, too. 

On top of that, I lost my owner role in the organization. I'm not sure if this is related, but it happened more or less at the same time, so I'm suspecting some connection.

Please advise on how to prevent this from happening again...

Best, Florian

### PR DESCRIPTION
**Pull request by tarebyte**
Will fix #332 still need some failing tests.

/cc @johndbritton

### CODE REVIEW

**Comment by johndbritton** [comment]
:cool: this looks right once you update the tests.

**Comment by chortlehoort** [comment]
If someone is affected by this bug, what is the process for regaining ownership of an organization that Classroom took away?

**Comment by tarebyte** [comment]
@chortlehoort actually your scenario is different I think, did you yourself signup for an assignment on Classroom?

**Comment by tarebyte** [comment]
@chortlehoort I would say contacting [GitHub Support](https://github.com/contact) would be the best way to get your organization back.

I apologize for the inconvenience, we are currently migrating part of the application to the new org permissions and this scenario was an oversight on my part.

**Comment by chortlehoort** [comment]
@tarebyte Yes, I did sign up for one of the assignments with my TA's to show the students how the process worked.  I'll ping support then about my issue.

**Pull request merged**
