### PR TITLE
Migration: Set User `last_active_at` value

### PR DESCRIPTION
**Pull request by cyhsutw**
This pull request is the first part of migration for #619.

It:
- Creates `last_active_at` column in the `users` table
- Sets the `last_active_at` values for existing users
- Sets the `last_active_at` value for the newly created users

/cc @tarebyte

### CODE REVIEW

**Comment by tarebyte** [comment]
This looks good, thanks @cyhsutw!

**Comment by cyhsutw** [comment]
:cool: @tarebyte I'll resolve the conflicts now.

**Comment by tarebyte** [comment]
Nice catch @cyhsutw!

**Comment by cyhsutw** [comment]
@tarebyte Thanks! 

Let me check my other pull requests to ensure that the schema version is correct.

**Comment by tarebyte** [comment]
@cyhsutw is this good to go?

**Comment by cyhsutw** [comment]
@tarebyte Yep, I just updated the versions of the migrations, I think it's ready to 🚢

**Comment by tarebyte** [comment]
Deployed, and migration/data transition was successful

**Pull request merged**
