### PR TITLE
Fix chewy jobs

### PR DESCRIPTION
**Pull request by mkcode**
@tarebyte - I forgot to let you know to add the following as well to get activejob and chewy to play nice together. This wraps sidekiq job runs in the Chewy `atomic` strategy.

This will fix these errors: https://github-education.airbrake.io/projects/116727/groups/1562757900403702415

### CODE REVIEW

**Comment by tarebyte** [comment]
@mkcode I just tried this locally and still get the following error:

```
2015-11-29T04:54:07.595Z 2788 TID-owzwu560g WARN: {"class"=>"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper", "wrapped"=>"DestroyResourceJob", "q
ueue"=>"trash_can", "args"=>[{"job_class"=>"DestroyResourceJob", "job_id"=>"2bfbb0d2-f243-47da-90cf-67e80e0727c8", "queue_name"=>"trash_can", "arguments"=>[{"_aj_globalid"=>"gid:
//classroom/Organization/5"}], "locale"=>"en"}], "retry"=>true, "jid"=>"ca31932f44dee9a0a5f716a3", "created_at"=>1448772847.469347, "enqueued_at"=>1448772847.46942, "error_messag
e"=>"Index update strategy is undefined in current context.\nPlease wrap your code with `Chewy.strategy(:strategy_name) block.`\n", "error_class"=>"Chewy::UndefinedUpdateStrategy
", "failed_at"=>1448772847.593291, "retry_count"=>0}
23:54:07 worker.1        | 2015-11-29T04:54:07.595Z 2788 TID-owzwu560g WARN: Chewy::UndefinedUpdateStrategy: Index update strategy is undefined in current context.
23:54:07 worker.1        | Please wrap your code with `Chewy.strategy(:strategy_name) block.`
```

**Comment by mkcode** [comment]
@tarebyte - I had put the chewy.rb in config rather than chewy/initializers. Good catch. Please try again.

**Comment by mkcode** [comment]
@tarebyte - Ok! Got the right file that time! Please try again now. Should be good to go.

**Comment by mkcode** [comment]
and we needed to add `/lib` to the autoload paths as well. Good to go.

**Comment by tarebyte** [comment]
@mkcode it works for me now, thank you!

**Pull request merged**
