### PR TITLE
Add message indicating empty unlinked user list

### PR DESCRIPTION
**Pull request by EricPickup**
## Problem

Related to #2190 

We have no message indicating when/why the unlinked github user list is empty.

## Solution

Add a message!

**Before**
image

**After**
image

### CODE REVIEW

**Comment by d12** [comment]
Can we go one step further and remove the "Select an unlinked..." prompt in this case? It doesn't make sense if there isn't anything to select.

**Comment by EricPickup** [comment]
@d12 done!
image

**Comment by stephaniegiang** [comment]
Nit pick: The sentence is kind of hard to read and is long. Maybe can do this:

```
There are no GitHub accounts to link. GitHub accounts will appear when a student:
- Has accepted an assignment
- Is not linked to a roster identifier
```

Doesn't have to be exactly that. Just a suggestion.

**Comment by EricPickup** [comment]
@stephaniegiang I think that separating it in the list format implies an "either or" with those two points (i.e. they will appear if they have accepted an assignment in the classroom _and/or_ also if they're not linked). For now I'll deploy this but if we see any more confusion we can adjust it later 👍

**Pull request merged**
