### PR TITLE
New site design (WIP)

### PR DESCRIPTION
**Pull request by jasonlong**
This lays down the basics of the new styles proposed in https://github.com/education/classroom/issues/49#issuecomment-132236899. I'm hoping this gives @tarebyte the building blocks needed to get things wrapped up.

There were a couple of places I didn't get to yet (e.g. the assignment details page with the list of names and URLs comes to mind). I'm happy to jump back in and help wrap up these loose ends.

I also tweaked some copy here and there to better match our GitHub voice, but I didn't make a full audit or anything.

Here are a handful of screenshots.

screen shot 2015-08-19 at 9 24 09 am

screen shot 2015-08-19 at 9 58 00 am

screen shot 2015-08-19 at 11 02 58 am

screen shot 2015-08-19 at 11 20 45 am

screen shot 2015-08-19 at 1 32 59 pm

screen shot 2015-08-19 at 1 49 35 pm

screen shot 2015-08-19 at 1 48 38 pm

screen shot 2015-08-19 at 2 24 26 pm

Note the bit.ly links here are placeholders.

/cc @johndbritton 
/fyi @cameronmcefee @jglovier

### CODE REVIEW

**Comment by johndbritton** [comment]
This is great. Thanks for jumping in @jasonlong. Two things that jump out at me:

* The "invite users" screen should include the green bar with the org name, since it's an org specific action.
* I'm no designer, but I feel like I want to see the icons for individual and group on the pages where you're creating assignments.

**Comment by jasonlong** [comment]
Those make sense to me @johndbritton. 

@tarebyte I was going to let you take the next pass, but let me know if you need help with those items or anything else.

**Comment by tarebyte** [comment]
@jasonlong :+1: sounds good

**Comment by jglovier** [comment]
@jasonlong Looks great man!! Only feedback is that it might be helpful to Classroom admins to have an explanation of what an "organization" is on the blank slate. 

Maybe something that briefly states how should they think of an organization in their own context, and if they are familiar with GitHub orgs, how it maps to GitHub orgs (e.g. if they should use an org for their specific course, or for their school, or for make a new one each semester, etc).

**Comment by johndbritton** [comment]
Can we also display the logged in avatar like GitHub?

screen shot 2015-08-20 at 11 40 48 am

**Comment by tarebyte** [comment]
@johndbritton we can, as we have the users GitHub ID

**Comment by tarebyte** [comment]
@jasonlong can you rebase against the current master branch? That will fix your failing CI.

**Comment by tarebyte** [comment]
@jasonlong going from #107 what do you think would be a good way of handling that on the organization invitation page?

My thought is that we can show that they can be invited, but inform the classroom admin that user has to add a public facing email address in order to be added.

**Comment by jasonlong** [comment]
> The "invite users" screen should include the green bar with the org name, since it's an org specific action.

> I'm no designer, but I feel like I want to see the icons for individual and group on the pages where you're creating assignments.

I've added these changes.

**Comment by jasonlong** [comment]
> Can we also display the logged in avatar like GitHub?

I added that (which is just a hardcoded placeholder for now) and changed the sign out link to the door icon.

screen shot 2015-08-20 at 3 31 34 pm

**Comment by johndbritton** [comment]
:heart:

**Comment by jasonlong** [comment]
> going from #107 what do you think would be a good way of handling that on the organization invitation page?

It looks like you guys got that resolved. Is that right?

**Comment by tarebyte** [comment]
@jasonlong what's the recommendation for handling flash messages?

screen shot 2015-08-21 at 20 55 14

**Comment by jglovier** [comment]
>what's the recommendation for handling flash messages?

@tarebyte if the flash message is related to the content, something like this could work:

image

**Comment by jglovier** [comment]
@tarebyte the other option – if keeping it above the content header is preferable – is to simply make it a full screen width banner.

image

**Comment by jasonlong** [comment]
Yeah, either of those is :cool:. If you go full-width, I'd probably put the banner below the green org banner though.

**Comment by tarebyte** [comment]
@jasonlong just implemented the "dangerzone" text, is this :+1: 

screen shot 2015-08-23 at 07 30 42

**Comment by jasonlong** [comment]
Cool, LGTM!

**Comment by tarebyte** [comment]
This is the individual assignments page
screen shot 2015-08-23 at 23 53 18

This is the group assignments page (this one still needs some :green_heart: 
screen shot 2015-08-23 at 23 53 27

Blank slate example
screen shot 2015-08-23 at 23 53 31

I still needs to style the app more, but I think this is in a mergable state. I'm going to merge this and continue working.

**Comment by tarebyte** [comment]
Thanks @jasonlong for the help, you really saved the day :sparkles:

**Comment by tarebyte** [comment]
And thank you to everyone else who offered feedback :grin:

**Comment by jasonlong** [comment]
:metal::smiley_cat::metal:

**Comment by jglovier** [comment]
sean-connery-fist-pump-us-open

**Pull request merged**
