### PR TITLE
Centralized ElasticSearch model and index lookup

### PR DESCRIPTION
**Pull request by johndbritton**
Kept some of the changes from https://github.com/education/classroom/pull/1629 but dropped the rake task.

### CODE REVIEW

**Comment by johndbritton** [comment]
@BenEmdon It turns out that the rake tasks included with Chewy seem to work fine. 

See: https://github.com/toptal/chewy#chewysync for more info.

My only concern is around rate limiting during the sync, but so far it doesn't seem to be a problem.

**Comment by johndbritton** [comment]
We should also investigate this:

https://github.com/education/classroom/blob/e5f356aef05d1d581b94aa7e618c1673fa4b144d/app/jobs/last_active_job.rb#L18

I don't think it actually reindexes the user.

**Comment by BenEmdon** [comment]
> It turns out that the rake tasks included with Chewy seem to work fine.

Were you able to run the chewy sync task without being rate limited?

**Comment by BenEmdon** [comment]
> I don't think it actually reindexes the user.

I guess we should remove this then:

https://github.com/education/classroom/blob/e5f356aef05d1d581b94aa7e618c1673fa4b144d/app/jobs/last_active_job.rb#L18

**Comment by johndbritton** [comment]
> Were you able to run the chewy sync task without being rate limited?

I was able to do successfully run `rake chewy:reset[organization]` which created a new index from scratch for that model.

**Pull request merged**
