### PR TITLE
Improve autocomplete suggestions for empty query

### PR DESCRIPTION
**Pull request by cyhsutw**
Use [list your repos](https://developer.github.com/v3/repos/#list-your-repositories) API for empty autocomplete query.

- remove github_id param from GitHub::Search
- update specs accordingly
- update cassettes accordingly

### CODE REVIEW

**Comment by tarebyte** [comment]
@cyhsutw so these two endpoints should be delivering the same content, I'd prefer to keep the user ID, because adding a id to the URL makes it unique for when we cache the search results.

Are we getting different results with your change?

**Comment by tarebyte** [comment]
@cyhsutw let me think on this one.

/cc @johndbritton

**Comment by johndbritton** [comment]
@cyhsutw Can you provide some visuals of what this changes?

**Comment by cyhsutw** [comment]
Here's the comparison:

| Before | After |
|:--------:|:-------:|
| before | after |

The difference here is that the new one shows the private repos of the user while the old one does not.

The reason is mentioned in @tarebyte's [comment](https://github.com/education/classroom/pull/592#issuecomment-219020163):

> https://developer.github.com/v3/repos/#list-user-repositories. It only lists public repositories.

**Comment by cyhsutw** [comment]
Actually I think these changes are making the code a little bit more hard to read (with the `nil` param).

**Comment by johndbritton** [comment]
@cyhsutw Did you see my comment here: https://github.com/education/classroom/issues/420#issuecomment-218819356

Maybe a better solution would be to improve what the user sees in the dropdown with some help text rather than just listing repositories. "Start typing a repository name" or similar

**Comment by cyhsutw** [comment]
@johndbritton Thanks for the information. 

I also agree that your approach will be a much better solution. 

Close this in favor of #598.

**Pull request closed without merging**
