### PR TITLE
Add link to apply for discount on assignment settings page

### PR DESCRIPTION
**Pull request by rabelmarte**
Hey everyone!

I recently stumbled upon GitHub Classroom and I think that Spark (a student outreach organization that focuses on inspiring and educating K-12 students on the wonders of technology) might just jump on board.

At the same time, I would like to dig in a little bit more deeper and help out. Therefore, I started by tackling a simple request #693.

Here's a preview of what it looks like on the new group assignment page.
screen shot 2016-09-08 at 9 40 00 pm

I look forward to working with all of the contributors!

### CODE REVIEW

**Comment by tarebyte** [comment]
Hi @rabelmarte thanks for the pull request!

This seems like something that should be more prominent on the page, and maybe something we should only show when the organization does not have any private repositories.

What do you think?

**Comment by rabelmarte** [comment]
You’re right 😺! I shall look into the project a little bit more to get the flow of it and then I’ll give it another try!

**Comment by rabelmarte** [comment]
As for the prominency, is this closer to what we had in mind @tarebyte ? 

screen shot 2016-09-10 at 10 21 03 pm

**Comment by tarebyte** [comment]
@rabelmarte something like that I think would work.

**Comment by Shekharrajak** [comment]
@rabelmarte , If you are not active, Can I work on it ?

**Pull request closed without merging**
