### PR TITLE
[WIP] Move rosters to a new tab and rename to students

### PR DESCRIPTION
**Pull request by stephaniegiang**
## What
Part of https://github.com/education/classroom/issues/2268
This PR moves rosters for ease of access. We also renamed rosters to students so that it is more clear. Rosters used to live in the settings tab. 

| Action | Screenshot |
|--------|------------|
| View of all students in classroom | image |
| Creating a new roster | image |
| Deleting roster | image |

### CODE REVIEW

**Comment by EricPickup** [comment]
I **love** the idea of moving the roster out of settings and into here.

I'm not sure about renaming everything "roster" to "students" because I think a decent chunk of classrooms don't use rosters and this could get confusing. E.g. a classroom without a roster sees the "Students" tab and is confused because they've had 30 github users accept their assignment but their students list is empty because they didn't use rosters.

This could be avoided by adding a small description to the top of the "Students" tab?

**Comment by EricPickup** [comment]
@femmebot @stephaniegiang nevermind, I can see on the roster setup screen you describe it pretty well. I was looking at the other tabs (after roster creation) and noticed there wasn't any description of rosters.

LGTM 😄

**Comment by stephaniegiang** [comment]
@femmebot are we good to go with this PR? I'll fix the errors and then I can deploy.

**Comment by stephaniegiang** [comment]
Oh that looks cool, I'll look into it 😃

**Comment by stephaniegiang** [comment]
@femmebot I don't think we can do a popover, just because of how the navigation is built. But we can do a flash message.

**Comment by stephaniegiang** [comment]
@femmebot For sure! I'm excited for the features page 😄

**Comment by andrewbredow** [comment]
Closing, we're taking this in a different direction.

**Pull request closed without merging**
