### PR TITLE
Changing labels from `group of teams` to `set of teams`

### LINKED ISSUE #601: Workflow - What if I delete this team?
Hello guys,

It is my first time using git classrom, and I'm not certain how the workflow goes.

My steps until now was:

Before EVERYTHING:

1. I've created a "startup repository" to give as assignment start point code (exwumpus)
2. I've created 6 teams and invited the students in each, accordingly to my own division of the class.

Now, with all set, I went to create a new ASSIGNMENT:
1. Set assignment title (pretty straight)
2. Private (easy)
3. Start code (done)
4. Maximum members per team: 7 (*)
5. Existing group of teams by date. (**)

Then I WAITED... :)
After a day or two, the first member created the assignment. For my surprise, I didn't know, but classroom created another team with only one member.

Lets talk with pictures.

Teams created by me are the ones in the image bellow that I can "leave". And the only one I can "Join" was created by classroom:

image

Well, I don't want it. Can I delete it?

If I go to classrooms, I can see the new repo there:

image

So I went into the repo configuration and added the correct team:

image

I also went to **MY** the team configuration to check:

image

And the **CLASSROOM** team doesn't have any members:

image

----

Bottom line: it is duplicating the teams I already set and put members in.

Can I delete the **classroom** team, or this will break/bug my assignment?

Also, what am I doing wrong with the workflow? Why I have this effort of creating the teams and setting them not recognized by the application?

Thank you!

(*) 4. Maximum members per team: 7

I told them to create groups of 5, but let a range of +-2 to be sure there is room for everyone. So I would like to suggest to ask not only the maximum, but also the "minimum", or a range. 

(**) 5. Existing group of teams by date.

Here, just by date may be trick. Maybe if we could list in a comma-separated list all the teams it would be more precise. Maybe this is the problem I'm having here.

Thanks all for any input clarifying the workflow (and suggesting new ways of doing it, also welcomed!)

### PR DESCRIPTION
**Pull request by dinever**
Change the text label to avoid misunderstanding

Closes #601 #615

### CODE REVIEW

**Comment by tarebyte** [comment]
@dinever thanks for updating these.

From a comment in https://github.com/education/classroom/issues/615#issuecomment-222860889 it might also be helpful to give a better name for the set of teams.

What are your thoughts on this?

**Comment by drbeco** [comment]
Do you mean the gray area?

**Comment by dinever** [comment]
Hi @drbeco 

This is a preview of the change:

screen shot 2016-06-04 at 8 49 33 pm

As you can see, the first label is modified from `group of teams` to `set of teams`.

I wonder if you have any suggestions or ideas on a better name for `set of teams`.

Thanks for the feedback in advance! 🙇

**Comment by drbeco** [comment]
Yes, please. The word reusable is misleading.

You may say it in both or in none.

Just an option:

* Reuse an existing set of teams
* Or create a reusable set of teams

Or

* Choose an existing set of teams
* Or create a new set of teams

Pair: Reuse/reusable or existing/new. Not existing/reusable, that doesn't fit properly in poor vocabulary. It may sound a bit pedantic, I know, but trust me it will make it clear.

**Comment by tarebyte** [comment]
> Choose an existing set of teams
> Or create a new set of teams

@dinever let's go with this option

**Comment by dinever** [comment]
@tarebyte 

Thanks! This is done.

**Pull request merged**
