### PR TITLE
Authentication API

### PR DESCRIPTION
**Pull request by sahilshekhawat**
We can build most of the required parts and then merge or start merging in small parts like this authentication API.

### CODE REVIEW

**Comment by tarebyte** [comment]
@sahilshekhawat, we've never really discussed an API for Classroom. What is the use case for this?

**Comment by sahilshekhawat** [comment]
This is a part of what I proposed for my GSoC project. Not necessarily an entire API but some parts which will be consumed by a desktop client for teachers to clone submission and do stuff. I talked to @johndbritton about this during our meeting. I thought why not start discussing the implementation right away.

Also, can we please have a mailing list where we can discuss things?

**Comment by tarebyte** [comment]
@sahilshekhawat I'm very against email mailing lists on principle that we have better tools at our disposal.

I'd rather we open issues and have discussions there. We have GitHub, we should use it.

**Comment by sahilshekhawat** [comment]
Sure, let me open an issue to discuss API.

**Comment by johndbritton** [comment]
> Also, can we please have a mailing list where we can discuss things?

Definitely prefer to stick to GitHub issues.

**Comment by sahilshekhawat** [comment]
Should I add get organizations and assignment endpoints here or should I raise another PR?

**Comment by sahilshekhawat** [comment]
I waiting for this PR to be merged before I raise another PR extending this work.

**Comment by tarebyte** [comment]
@sahilshekhawat I'm not going to merge this pull request, we haven't had enough discussion about how an API would work or even _if_ we need an API.

None of the proposals have been accepted yet for GSOC, so it doesn't make sense to start including work for a project that may not actually be worked on this summer.

**Comment by sahilshekhawat** [comment]
@tarebyte No worries,  I was just letting you guys know that I am not working on this. Thanks

**Pull request closed without merging**
