### PR TITLE
Upgraded Rails to 4.2.5; Added cache to .travis.yml

### PR DESCRIPTION
**Pull request by jasnow**
* Upgraded Rails to 4.2.5
 * Added "cache: bundler" to .travis.yml file.
 * Add 2 lines to .gitignore to not force use of overcommit gem.
 * Fixed rubocop error and 3 scss-lint errors.
 * Later upgraded additional 5+ gems.

### CODE REVIEW

**Comment by jasnow** [comment]
new pull request

**Comment by jasnow** [comment]
All green now.

**Comment by tarebyte** [comment]
Thanks for your PR @jasnow I'll check this out soon, I just want to make sure everything runs ok on my staging instance.

**Comment by jasnow** [comment]
ok

**Comment by jasnow** [comment]
FYI: Also there is a new version of **sprockets** but your Gemfile is locked down.

**Comment by jasnow** [comment]
Blocked by PR #363, so stopping for now.

**Pull request closed without merging**
