### PR TITLE
Add functionality to destroy groups

### LINKED ISSUE #730: Teams cannot be deleted from Classroom once created
### The Problem
- We are currently using GitHub Classroom to manage the on-demand courses for GitHub Training. 
- We are adding all new students to a single team, however I feel confident this would also be an issue if we had any number of teams. 
- At this time, **there is no way to prevent users from creating new teams for the assignment.** 
- There is also **no way to delete a team from classroom** once it has been made (even if we delete the associated team from the github org).

Are these features we can consider adding? 

Thank you!

### PR DESCRIPTION
**Pull request by BelieveC**
Destroys groups and associated group_assignment_repos from stafftools

Closes #730

### CODE REVIEW

**Comment by nwoodthorpe** [comment]
@BelieveC The code lgtm. Would you be able to add a couple controller specs for the new action?

**Comment by nwoodthorpe** [comment]
Also a small style thing to fix, it's from a recent rule change we made in the linter.

**Comment by BelieveC** [comment]
@nwoodthorpe I will add the specs for new actions.

**Comment by BelieveC** [comment]
@nwoodthorpe, I have added test for destroy action :smile:

**Comment by cboettig** [comment]
The ability to destroy groups would be a huge help.  (Though it would be particularly nice if groups could entirely be managed through the GitHub API that would be even better, since it would automatically give an interface to destroy and otherwise manage groups).

**Comment by cboettig** [comment]
@nwoodthorpe Your July 24 comments looked good for this contribution. Is the hold up due to the failing travis check here?

**Comment by d12** [comment]
@cboettig yes, we cannot merge this with failing specs.

**Pull request closed without merging**
