### PR TITLE
Make N+1's more noticeable

### PR DESCRIPTION
**Pull request by tarebyte**
I was running the app and realized that there are n+1 queries happening but I just missed them

What do we think about adding these notices to airbrake so that they are brought to our attention in a more obvious way?

/cc @johndbritton @mkcode

### CODE REVIEW

**Comment by mkcode** [comment]
Great. Getting the bullet errors in airbrake is a good idea. 

Bullet.raise - https://github.com/education/classroom/pull/370/files#diff-412a4fba00cba5ff704676f839824c0fR15 - in #370 should be raising errors for detected n+1 queries in test mode - and therefore failing CI builds and now allowing deploys. So an N+1 in production should indicate that there is no test coverage of that code. @tarebyte - can you verify this?

**Comment by tarebyte** [comment]
You got it!

**Comment by johndbritton** [comment]
> What do we think about adding these notices to airbrake so that they are brought to our attention in a more obvious way?

:+1:

> So an N+1 in production should indicate that there is no test coverage of that code.

Yep, means we need some more test coverage.

**Comment by tarebyte** [comment]
Will revisit this another time, closing due to staleness.

**Pull request closed without merging**
