### PR TITLE
Push Starter Code for Assignments and GroupAssignments

### PR DESCRIPTION
**Pull request by tarebyte**
This gives the user the option to push starter code when the user accepts goes to the invitation url.

push_starter_code

/cc @johndbritton

### CODE REVIEW

**Comment by tarebyte** [comment]
This still needs tests, but I wanted an initial look over

**Comment by tarebyte** [comment]
Tested it on staging, good to go. @johndbritton if you have any suggestions or concerns let me know! :grin:

**Comment by johndbritton** [comment]
:zap::zap::zap::zap::zap: Nice!

**Comment by johndbritton** [comment]
Looks good. How do you handle a failed push? Does the student have any way to trigger the push again if it doesn't work the first time around?

**Comment by tarebyte** [comment]
As of right now, they can refresh the page and it will trigger the process again.

**Comment by tarebyte** [comment]
There should probably be a better way to do it though.

**Pull request merged**
