### PR TITLE
Configure CI to test against multiple Postgres database versions

### PR DESCRIPTION
**Pull request by thebradbain**
## What

Part of #1894 

In ensuring the planned postgresql upgrade goes as smooth as possible, configure CI to test against both the current (v9.4) and planned (v10.9) postgresql versions.

Note: Travis does not support this capability out of the box, but they do provide [documentation](https://docs.travis-ci.com/user/database-setup/#multiple-database-builds) to do so. Nevertheless, after the upgrade, we will probably want to revert these changes, as it doesn’t make sense to test against two versions after the fact.

### CODE REVIEW

**Comment by tarebyte** [comment]
@thebradbain should we update the `pg` gem as well in this PR?

Awesome work btw ✨

**Comment by BenEmdon** [comment]
This :clap: is :clap: SO 👏 dope 👏

**Comment by thebradbain** [comment]
I was thinking upgrading the `pg` gem be a separate PR, as the current version is still technically compatible with the latest version of Postgres, it's just old. I can add it in this one though, if we feel they're related enough! @tarebyte

**Comment by tarebyte** [comment]
@thebradbain I'm fine with it being a separate PR.

**Pull request merged**
