### PR TITLE
Group Assignments

### PR DESCRIPTION
**Pull request by tarebyte**
This allows the user to create a public or private group assignment, and let the students create their own teams for the assignments

### CODE REVIEW

**Comment by tarebyte** [comment]
Example of creating a new group assignment with a bit of front ending

organization_front_end

**Comment by johndbritton** [comment]
Love that gif.

**Comment by tarebyte** [comment]
:sparkling_heart:

**Comment by tarebyte** [comment]
@johndbritton this is finally ready to ship, if you see something that you need changed let me know!

**Comment by johndbritton** [comment]
:bomb:

**Pull request merged**
