### PR TITLE
Roster form validation

### PR DESCRIPTION
**Pull request by Kadaaran**
Hi there ! 👋 

I found a bad user experience while creating a roster.
The form validation is in server side, so if the user did not fill one field out of the two required, all data is lost (as the page reloads after hitting the submit button).

screen shot 2018-01-17 at 23 40 33
screen shot 2018-01-17 at 23 40 40

It can be solved by just adding `required: true` into the HTML but we lose the custom error messages. The data will be sent to the controller only if both fields aren't empty.
In order to keep those error messages we can add some JS but I don't know if it's a good thing to do.

screen shot 2018-01-19 at 11 30 55

Does someone have a thought about it ? 🤔 

Thanks a lot ! 🙇

### CODE REVIEW

**Comment by tarebyte** [comment]
Honestly I'm fine with losing the custom error message for it not being blank if that means we don't have to make a round trip to the server and save people time.

**Comment by Kadaaran** [comment]
@tarebyte Ok then I removed from the form the custom error messages but as we use them elsewhere, I'm leaving them in `FormView`. It might not be "pretty" for the user but indeed we don't make a round trip to the server side 👍

**Comment by tarebyte** [comment]
@Kadaaran I know we technically don't need them, but just for consistency sake would you mind leaving the custom validation partials in?

That way if we add different validations that aren't just presence we don't have to go back and add them in.

**Comment by Kadaaran** [comment]
@tarebyte Sure ! (I did not think about that 🙈 )

**Pull request merged**
