### PR TITLE
issue #1010, CSS update stafftools.scss, show.html.erb

### PR DESCRIPTION
**Pull request by arolson**
Repositioned the Impersonate button in stafftools. Changes were made to files `app/assets/stylesheets/stafftools.scss` and `app/views/stafftools/users/show.html.erb`.

### CODE REVIEW

**Comment by nwoodthorpe** [comment]
Would we be able to do this without using `bottom`, `right` and `position: absolute`? Making things position absolute affects the flow of other elements, so styling things in the future might become more difficult because of this.

We have other buttons that are positioned correctly without using position: absolute, maybe look into those. Usually when we need to vertically center, my goto is flexbox.

Also, can you add a screenshot of the button after your change?

Thanks :)

**Comment by arolson** [comment]
@nwoodthorpe yea actually I was able to reproduce similar results using the flex-box. Thanks for the suggestions! The first image is of the css modification, the second is using the flex-box. This was my first attempt at playing with ruby apps, so it was kind of fun 😆 

* CSS:
screen shot 2017-07-16 at 10 55 02 am

* Flexbox: 
screen shot 2017-07-16 at 12 19 53 pm
wrapped the `<h4>` header and the `<p>` tag in a `<div>` then did the same with the `<a>` tag.
Treated them as separate flex-items.

**Comment by tarebyte** [comment]
👋

**Comment by tarebyte** [comment]
👋 

I think my changes in #1021 will actually solve the issue here without the very specific CSS

https://github.com/education/classroom/pull/1021/files#diff-4cc49612e087993b6f5b7df19a58c7fcR83

**Comment by nwoodthorpe** [comment]
Yeah, that looks better. Sorry @arolson, this bug was caused by something bigger. I'm going to close this in favor of #1021.

**Pull request closed without merging**
