### PR TITLE
Handle API Errors Better

### PR DESCRIPTION
**Pull request by tarebyte**
@kdaigle, @johndbritton I'm starting to work on better error handling when it comes to Octokit.

Here is my thought process:

Instead of having `GitHubClient` create models such as `GitHubOrganization`, `GitHubTeam`, `GitHubRepository` etc. Those models are the only ones that can make the `API` calls on behalf of the user and will have the corresponding error handling.

I updated the `OrganizationsController` to handle the new style for authorization.

Let me know what you think!

### CODE REVIEW

**Comment by johndbritton** [comment]
Looks legit.

**Comment by tarebyte** [comment]
@johndbritton, here is what a successful invitation redemption looks like now.
derp

**Comment by tarebyte** [comment]
@johndbritton these are examples of errors that the user can see now.
screen shot 2015-07-06 at 18 49 57
screen shot 2015-07-06 at 18 52 15

**Comment by tarebyte** [comment]
@johndbritton I'm going to merge this so I can continue on with `GroupAssignments`, if you see anything holler :grin:

**Comment by johndbritton** [comment]
:cool:

**Pull request merged**
