### PR TITLE
Explicit Assignment Submission

### PR DESCRIPTION
**Pull request by cyhsutw**
Hi all,

This pull request is a part of #667. It's a minimal implementation of assignment submission using GitHub releases.

Instead of of building the _explicit assignment submission_ feature and the _due date_ feature together, I would like to separate these two features so it will be easier to understand.
### Assignment submission flow for students

In this pull request, students can specify which version of their works should be submitted for grading.

This is done by using GitHub's [release feature](https://help.github.com/articles/about-releases/).  Students will need to [create a release](https://help.github.com/articles/creating-releases/) of the work they'd like the teachers to grade:

student-submit
### Accessing students' submissions

Teachers can view the submission statuses of each assignment/group assignment:

teacher-panel

Clicking the _submitted {time ago}_ will bring teachers to the release page on GitHub where teachers can download the compressed source files and viewing students' note of their submissions.

Note: 
- This feature is placed under Flipper using flag `explicit_assignment_submission`.
- Currently, the time of the submission is set to the `published_at` time of the release.

Thanks for reading, I would love to hear your feedback on this 😄

### CODE REVIEW

**Comment by dhowe** [comment]
This is really great. One additional feature to consider would be to allow a teacher (or grader) to download the full set of submissions/releases for an assignment as a zip...

**Comment by jayvdb** [comment]
As I asked at https://github.com/education/classroom/issues/379#issuecomment-249340969 , does using releases allow for the submission to not be edited undetected after the submission date? I would feel much more confident if the git hash of the released commit was stored outside of the student repo on submission, so I can see if they changed the repo after it.

**Comment by dhowe** [comment]
Yes @jayvdb raises an important point -- we need to be able to easily verify that a specific release can not be edited without changing its timestamp...

**Comment by cyhsutw** [comment]
Hi @dhowe and @jayvdb 

Sorry for the delay. 😓  And thanks for identifying the problem, I didn't noticed that the tags can be force pushed. 

One possible way to address this issue is as mentioned, storing the SHA outside the repository. 
Another way is creating a [commit status](https://developer.github.com/v3/repos/statuses/) once a release is created, and the good news is that commit statuses cannot be modified. By looking at the commit status, we can be confident about the submission is not modified after it was created. 

I'm currently working on this 🚧 , and hope to bring it to you as fast as I can. 

Thanks again for your valuable feedback and suggestions.
I would appreciate hearing your thoughts on this 😄

**Comment by jayvdb** [comment]
To make sure I understand, Github Classroom will watch releases, and will give the "success" status when a release is created, but not give the "success" status when a release is modified?

That still concerns me, as the student can destroy a potentially good submission by amending the release, and the teacher wont be able to see what the submission was, because the SHA has disappeared.

In the model where students use the same repo for a multi-stage assignment, I'd really like to have the submitted SHA so I can see exactly what they submitted at each stage.

Even if the SHA isnt stored permanently anywhere, perhaps the SHA could be emailed to the teacher and student after submission, as a 'receipt'.

**Comment by cyhsutw** [comment]
@jayvdb Thanks for the feedback, it's really nice to have feedback from teachers who use GitHub Classroom. 

> GitHub Classroom will watch releases, and will give the "success" status when a release is created

That's correct. Let me explain it more with an example:

Say a student wants to submit the code at commit `123abc`.
By creating a release on GitHub:  

1. A Git tag will be pushed to the repo (let's call it `submission-1` for example) and the tag `submission-1` will point to commit `123abc`. 
2. GitHub Classroom will add a commit status to commit `123abc`. If we use GitHub API to check the status for commit `123abc`, we will see something like this:

    ```ruby
    {
      id: 771953014,
      state: "success",
      description: "Assignment submitted at 2016-09-27 01:02:42 UTC",
      context: "github-classroom/assignment-submission",
      created_at: "2016-09-27T01:02:42Z",
      updated_at: "2016-09-27T01:02:42Z",
      creator: {
        login: "classroom[bot]",
        id: 10469176,
      }
    }
    ```

This commit status can infer:

1. Whether a commit is counted as a submission
2. The submission is overdue or not (it's reliable as the timestamp is issued by GitHub.com which cannot be changed by students)

And for students who force-pushed the tags, a new commit status will be created, so there's no way to cheat.

> the student can destroy a potentially good submission by amending the release, and the teacher wont be able to see what the submission was, because the SHA has disappeared

Once a release is created, GitHub will keep a snapshot of the repo at the SHA, and it will remain stored even if the SHA cannot be found in the entire 
commit history.

The teachers should be able to get the code *unless the students delete the releases*.


I would appreciate hearing your thoughts on this, thanks 😄

**Comment by jayvdb** [comment]
Scenario:

1. Student submits almost complete solution 2 hours before deadline
2. Student resubmits complete solution 10 mins after the deadline.  They use the release edit/delete functionality to do this.
3. I go to look at their solution the following day, and want to see their pre-deadline submission

Can I see their submission before the deadline?  If not, I have two alternatives:
1.  completely fail the student, as I cant see their pre-deadline submission, or 
2.  invalidate the fairness of the assignment by retrospectively allowing only this student to have used 10 more minutes.  And all the trust issues that creates.

**Comment by cyhsutw** [comment]
@jayvdb Thanks for the feedback!

I've added your suggestions into the roadmap, please see #667.

**Comment by nwoodthorpe** [comment]
Closing for inactivity. Feel free to re-open if there's progress.

**Pull request closed without merging**
