### PR TITLE
Octopoller.try 

### PR DESCRIPTION
**Pull request by BenEmdon**
## What
@d12 [said](https://github.com/education/classroom/pull/1400#discussion_r203068588) that it would be nice to have a a function that attempts a action given a # of attempts. This PR proposes a new Octopoller function `try`.

It's API is very similar to the `poll` API:
```ruby
Octopoller.try(wait: 1.second, attempts: 2) do
  result = put_in_usb_stick()
  :retry if result.success?
end
```

There is also an exponential backoff retry:
```ruby
start = Time.now
Octopoller.try(wait: :exponentially) do
  puts (Time.now - start).seconds
end

# => 0 seconds
# => 0.5 seconds
# => 1 second
# => 2 seconds
# => 4 seconds
# ....
# Tried maximum number of attempts (Octopoller::TooManyAttemptsError)
```

What are your thoughts and ideas about the API? Can it be improved? Is this what you hoped it would look like?

### CODE REVIEW

**Comment by d12** [comment]
I'm curious why this needs to be another method. It seems like the behavior is almost identical, it's just a slightly different way of retrying. Could this be achieved with kwargs for `poll`? If not, could `poll` and `try` be renamed to better describe their differences?

**Comment by BenEmdon** [comment]
> Could this be achieved with kwargs for `poll`?
  @d12 

My question is what should happen if you pass in a `timeout` and `attempts`? Can they each have a default value?
If Ruby supported function overloading I would have done that. What would a Rubiest do in this situation?

**Comment by d12** [comment]
You could raise an ArgumentError if they're both provided, and make it
clear you can only use one in the comment.

**Comment by d12** [comment]
I'm not sure if this is good for review let, cc me when it is!

**Comment by BenEmdon** [comment]
## Update
Since your feedback @d12 I merged `try` and `poll` into the `poll` function. The API for Octopoller is now:
```diff
+ def poll(wait: 1.second, timeout: nil, retries: nil)
- def poll(wait: 1.second, timeout: 15.seconds)
```

## Overview
* Poll with a timeout:
  ```ruby
  Octopoller.poll(timeout: 15.seconds) do 
    puts "🦑"
    :re_poll
  end

  # => "🦑"
  # => "🦑"
  # ...
  # Timed out patiently (Octopoller::TimeOutError)
  ```

* 🆕 Poll with a retries:
  ```ruby
  Octopoller.poll(retries: 2) do 
    puts "🦑"
    :re_poll
  end

  # => "🦑"
  # => "🦑"
  # => "🦑"
  # Tried maximum number of attempts (Octopoller::TooManyAttemptsError)
  ```

* 🆕 Poll with exponential backoff:
  ```ruby
  start = Time.now
  Octopoller.poll(wait: :exponentially, retries: 4) do 
    puts Time.now - start
    :re_poll
  end

  # => 0.5 seconds
  # => 1 second
  # => 2 seconds
  # => 4 seconds
  # => 8 seconds
  # Tried maximum number of attempts (Octopoller::TooManyAttemptsError)
  ```

This is ready for review @d12 👀

**Pull request merged**
