### PR TITLE
creating new lms git hub web change to class room to  main hall

### PR DESCRIPTION
**Pull request by kavindyasinthasilva**
I wont change this  class room , this  concepts  cant  access our all student ,this is include online test quiz and exams

### CODE REVIEW

**Comment by d12** [comment]
:wave: I'm not sure what the intent of this PR is, could you expand?

It also looks like you're merging master into another branch, not the other way around. Was that intended?

**Comment by kavindyasinthasilva** [comment]
thank you ,  who is develop this web site ?

**Comment by d12** [comment]
@kavindyasinthasilva That'd be me and the GitHub Education team, how can we help?

**Comment by kavindyasinthasilva** [comment]
i am using  git hub education community and how to join it . and i can make pull request and commit .
   https://education.github.community/u/kavindyasinthasilva/summary

**Comment by d12** [comment]
Pull requests welcome, but I'm not sure what this PR is supposed to do. Our issues are a good place to start if you're looking for open source work to do.

**Comment by kavindyasinthasilva** [comment]
how to help me git hub class room. and  can i  contribute continue?

**Pull request closed without merging**
