### PR TITLE
Settings buttons look too similar

### LINKED ISSUE #513: Identical 'Settings' buttons in the same view
screenshot 2016-03-23 10 07 15

There's two identical `Settings` buttons. I know, I know – if you pay enough attention, they are in different contexts / ui boxes:
- the 'Kipos' classroom header, and
- the ui box owned by the 'test' assignment.

Still, it doesn't feel like a good solution, it's not _awesome_ nor it's straightforward to understand. The fact that the buttons are so apart from their modifying elements doesn't make it any easier.

Renaming the first one's label to `Classroom Settings` helps, but it's just a patch, not a solution.

---

Also, any reason not to add the octicon gear icon?

### PR DESCRIPTION
**Pull request by tarebyte**
Closes #513 

screen shot 2016-03-23 at 10 30 57 am

screen shot 2016-03-23 at 10 31 16 am

/cc @jasonlong @johndbritton

### CODE REVIEW

**Comment by jasonlong** [comment]
Looking at it, I might try making the assignment settings button gray. Either that or a regular link with the icon.

**Comment by tarebyte** [comment]
Option 1
screen shot 2016-03-23 at 10 40 47 am

Option 2
screen shot 2016-03-23 at 10 44 40 am

@jasonlong here are your two suggestions

**Comment by jasonlong** [comment]
I think I prefer the gray button. What do you guys think? Regardless, I think this direction solves the problem of the similar looking buttons pretty well.

**Comment by tarebyte** [comment]
I'm good with the button

**Comment by dasilvacontin** [comment]
@jasonlong @tarebyte All buttons in `site-content-cap` look like actual buttons, with a border. The color difference may be good since 'Settings' is not a 'creation' action – easier to associate with the outcome.

**Comment by dasilvacontin** [comment]
Still, 'Update your permissions' is not a 'creation' action, yet the button is green. But it's the main action of that dialog. Settings is not even an action, links to a secondary view..

Gray button and text changes LGTM. Looks nice and it's much easier to understand the buttons' purpose. :) :+1:

**Comment by johndbritton** [comment]
Looks great, I'm happy with either.

**Comment by tarebyte** [comment]
alrighty gray buttons it is, thanks everyone!

**Pull request merged**
