### PR TITLE
Fix tabs not restoring selected tab after refresh

### PR DESCRIPTION
**Pull request by sethb157**
This bug caused the roster tabs on the management page
to forget the currently selected tab on page refresh.
In order to fix this, the roster_tabs js file
has been replaced with a more generic manage-tabs
implementation, which both fixes the bug and makes the addition
of more tabs a little easier. All groups of tabs have been updated
to use manage-tabs.

NOTE: There are no tests attached to this yet. @Kadaaran suggested that I wait till the update to 5.2 is done, in order to test with capybara.

### CODE REVIEW

**Comment by d12** [comment]
Closes https://github.com/education/classroom/issues/1193

**Comment by BenEmdon** [comment]
Hey @sethb157 looks like we are on Rails 5.1 https://github.com/education/classroom/blob/d82ea459cc21a3f6d1e5d678402c3439a63ea633/Gemfile#L11

**Comment by sethb157** [comment]
@BenEmdon Shoot, just saw this. I'll add in testing and make another PR. Thanks for the reminder!

**Comment by BenEmdon** [comment]
This has become too stale for us to consider. If you decide to rework this PR please open an issue and tag `@education/classroom` with the feature request.

**Pull request closed without merging**
