### PR TITLE
Add GitHub's Primer and Remove asset gems

### PR DESCRIPTION
**Pull request by tarebyte**
From discussion in #5

This PR:
* Uses [bower](http://bower.io/) to manage vendored assets
* Installs [primer](https://github.com/primer/primer) (along with [octicons](https://github.com/github/octicons))
* adds `octicon` and `mega_octicon` view helpers with tests
* remove jquery-rails gem and replace it with jquery and jquery-ujs from the vendor folder
* Changes the application layout to make it more browser friendly

Not sure how I feel about checking the vendored assets into version control, but I really don't like gems that are just for assets (bootstrap-sass, jquery-rails etc).

Opinions?

### CODE REVIEW

**Comment by johndbritton** [comment]
> Not sure how I feel about checking the vendored assets into version control, but I really don't like gems that are just for assets (bootstrap-sass, jquery-rails etc).

I think you're fine to vendor stuff that comes from bower. It's not my favorite thing, but we even vendor gems in version control for speedier and more reliable deployments (one less dependency).

**Comment by tarebyte** [comment]
> t's not my favorite thing, but we even vendor gems in version control for speedier and more reliable deployments (one less dependency).

It seems better than trying to have bower install the dependencies on deployment to production for anything like that.

Also just so it's written down, there is currently an issue with octicons with the latest sprockets-rails github/octicons#50

**Comment by johndbritton** [comment]
:shipit:

**Comment by tarebyte** [comment]
Sounds good to me, I'll probably wait until github/octicons#50 gets resolved.

**Pull request merged**
