### PR TITLE
All assignment relationships

### PR DESCRIPTION
**Pull request by tarebyte**
This pull request is to setup the relationships for both kinds of `Assignments`, setup factories, and update tests

### CODE REVIEW

**Comment by tarebyte** [comment]
Just to give a different representation of the relationships

erd

**Comment by tarebyte** [comment]
@johndbritton also a lot of these views will be coming back in different forms, I just wanted to remove them just to clean things up

**Comment by tarebyte** [comment]
Going to :shipit:

**Comment by johndbritton** [comment]
:+1:

**Pull request merged**
