### PR TITLE
Improve starter code repo search experience

### PR DESCRIPTION
**Pull request by cyhsutw**
This is an implementation of @johndbritton's [comment](https://github.com/education/classroom/issues/420#issuecomment-218819356) in #420.

preview

Summary of changes:
- show suggestions only when the user starts typing (i.e. no suggestions for empty input)
- change `placeholder` of the starter code repo textfields

**TODO:**
- [x] Support selecting suggestion using arrow keys <kbd>↑</kbd> <kbd>↓</kbd>
- [x] Support closing suggestion list using <kbd>esc</kbd>
- [x] Update GIF for this pull request

**Questions:**
Since we no longer send empty query strings to the server side, should we remove the code that handles empty query strings (the *list my repo* part)? 🔥🔥🔥

### CODE REVIEW

**Comment by johndbritton** [comment]
I like this. What do you think @tarebyte?

@jasonlong Any tips from a UX perspective? We're changing this because users were confused about what to enter into the starter code selection box.

**Comment by tarebyte** [comment]
This looks good to me!

**Comment by johndbritton** [comment]
> Since we no longer send empty query strings to the server side, should we remove the code that handles empty query strings (the list my repo part)?

I'm always a fan of :fire: unused code. If we need it back in the future, it's in the project history :wink:

**Comment by jasonlong** [comment]
👍  Seems like a nice pattern to me.

The "Start typing a repository name" sounds slightly awkward. Would "Search repositories" work?

**Comment by johndbritton** [comment]
> Would "Search repositories" work?

I think so, let's go with that.

**Comment by cyhsutw** [comment]
Thank you for taking time reviewing the pull request! I really appreciate your kindly help.

I've changed the hints suggested by @jasonlong. Also set the 🔥  to burn down the unused code.

Going to work on the TODOs and will send the changes soon.

**Comment by cyhsutw** [comment]
Travis build failure seems unrelated, going to close and reopen this to trigger the build again. 

```
Starting Spring server with `/home/travis/build/education/classroom/vendor/bundle/ruby/2.3.0/gems/spring-1.7.1/bin/spring server --background` timed out after 10 seconds
```

**Comment by johndbritton** [comment]
@cyhsutw I was able to trigger the build on the build page. I don't know if that's restricted to project admins or not.

**Comment by cyhsutw** [comment]
@tarebyte @johndbritton  I think this is ready for review.

Let me summarize the changes:
- all of the requests for autocomplete are using the GitHub search API directly, no more *list your repo API*
- common key bindings are added to the search text field: 
  - <kbd>esc</kbd> for dismissing suggestions
  - <kbd>↑</kbd> <kbd>↓</kbd> for moving the highlighed the items
  - <kbd>enter</kbd> for confirming the selection

@johndbritton Thank you for triggering the build for me. I was unable to find the retry button for the build. I tried to log out and log back in on Travis and the button appears, looks like it might be some problems with my cookies or authentication stuffs.

**Comment by johndbritton** [comment]
👍 from me, but want to give @tarebyte a chance to do a more thorough review.

**Comment by cyhsutw** [comment]
@tarebyte Thanks for reporting the bug.
It's related `KeyboardEvent.key` which is not fully supported in some browsers.
I've switched back to `KeyboardEvent.keyCode` and tested in the latest version of Chrome, Firefox and Safari (I don't have Edge and IE 11, however, according to [MDN - KeyboardEvent.keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keycode) this should work with IE 6+ too).

**Pull request merged**
