### PR TITLE
Disable the "Download Repositories" button

### LINKED ISSUE #1589: Don't show download repo button unless there assignment repos
See https://github.com/education/classroom-assistant/issues/71#issuecomment-423628486 for details

### PR DESCRIPTION
**Pull request by BenEmdon**
This PR proposes we disable the "Download Repositories" button when there are no `assignment_repos`.

# Screenshots
#### When there is no assignment repos
screen shot 2018-11-09 at 3 51 39 pm

#### When there is assignment repos
screen shot 2018-11-09 at 3 51 15 pm

#### When there is no assignment repos
screen shot 2018-11-09 at 4 31 00 pm

#### When there is assignment repos
screen shot 2018-11-09 at 4 31 52 pm

Closes #1637, Closes  #1589
Reverts #1666

### CODE REVIEW

**Comment by BenEmdon** [comment]
@srinjoym when you have a moment would you mind taking a look at this?

**Comment by srinjoym** [comment]
@BenEmdon There was something going wrong with the `disabled` condition itself on some classrooms in production. I'll investigate a bit more over the weekend to try and figure out what was going on and let you know 🕵️

**Comment by BenEmdon** [comment]
This has been sitting for a while, would you be able to take a look @srinjoym ? 🔍

**Comment by BenEmdon** [comment]
This has been sitting for a while, would you be able to take a look @srinjoym ? 🔍

**Comment by BenEmdon** [comment]
@srinjoym friendly nudge 😉

**Pull request merged**
