### PR TITLE
Re #436 - Upgrade Sidekiq to 4.5.1

### LINKED ISSUE #436: Upgrade to Sidekiq 4.x
Speed improvements: http://www.mikeperham.com/2015/10/14/optimizing-sidekiq/

Upgrade guide: https://github.com/mperham/sidekiq/blob/master/4.0-Upgrade.md

### PR DESCRIPTION
**Pull request by cbetta**
Upgraded to latest version of Sidekiq which drops Celluloid dependencies and includes massive speed improvements. 

Re #436.

### CODE REVIEW

**Comment by tarebyte** [comment]
Thanks for the contribution @cbetta, I think there is more that we need to do here than just upgrade the gem based off of https://github.com/mperham/sidekiq/blob/master/4.0-Upgrade.md and my own experience trying to upgrade.

I'll give this a look sometime today or tomorrow.

**Comment by cbetta** [comment]
@tarebyte Not sure there is. I recently did an upgrade on another project and this is pretty much it. You do not use any Redis namespacing. I ran the app in development and tested the 1 background job you have and it seems to work fine.

**Comment by cbetta** [comment]
Obviously happy to get extra eyes on it to confirm :)

**Comment by tarebyte** [comment]
Pushed to a staging instance, looks good to me. Thanks @cbetta!

**Pull request merged**
