### PR TITLE
Add some og:images

### PR DESCRIPTION
**Pull request by dpedoneze**
Issue #306 

--

I didn't find a bigger logo so I resized the actual.

### CODE REVIEW

**Comment by johndbritton** [comment]
I definitely prefer without the shadow.

@jasonlong / @jglovier Do you have any feedback on these images? Right now our open graph image is just the screenshot from the blog post which is not really optimized for social sharing.

**Comment by jasonlong** [comment]
I'd prefer to see the `og:image` be very simple. Like just the wordmark on the green or dark gray background. And optionally the tagline below it.

**Comment by johndbritton** [comment]
@jasonlong You mean this copy:

> Classroom for GitHub
> Your course assignments on GitHub

With the first line as the wordmark?

**Comment by jasonlong** [comment]
Right. So something like this maybe. Though it feels slightly awkward to have GitHub at the end of both lines.

og-image

Alternatively, just the wordmark:

og-image-simple

These use the recommended 1200x630 dimensions.

**Comment by johndbritton** [comment]
@jasonlong What about something with the octicons from the homepage to break it up?

Can you provide a version with the word "course" rather than "class?"

**Comment by johndbritton** [comment]
I'm also fine with doing just the wordmark if that's preferred.

**Comment by dpedoneze** [comment]
way better :smile:

**Comment by jasonlong** [comment]
@dpedoneze Thanks for getting the ball rolling on this. I had completely overlooked this piece.

I like the Octicons idea @johndbritton. How about this?

og-image-icons

**Comment by tarebyte** [comment]
@jasonlong, looks great!

**Comment by jglovier** [comment]
:+1: :+1: on @jasonlong's direction. Def +:100: for the octicons, mostly to help imply some sense of context visually.

**Comment by johndbritton** [comment]
Closing this in favor of #313. Thanks for getting this started @dpedoneze, I attributed you as the author of https://github.com/education/classroom/commit/b7049316ecb0e2d8e449049e4fc0230a7a8ec002.

**Pull request closed without merging**
