### PR TITLE
Code documentation

### PR DESCRIPTION
**Pull request by tarebyte**
@kdaigle recommended that I use [TomDoc](http://tomdoc.org/) for documenting the Classroom's methods.

This is a WIP so feedback is always welcome!

### CODE REVIEW

**Comment by kdaigle** [comment]
:sparkles:

**Comment by tarebyte** [comment]
This will also include the docs for contributing and the README

**Comment by tjhorner** [comment]
Love your commit messages.

**Comment by tarebyte** [comment]
will revisit this soon, too much has changed here

**Pull request closed without merging**
