### PR TITLE
Add message of the day banner to top of the page

### PR DESCRIPTION
**Pull request by tarebyte**
From @johndbritton's request by setting the `MOTD` on the server environment variable we can show a special banner at the top of all pages.

This is what it looks like right now

screen shot 2016-01-07 at 12 14 37 pm

/cc @jasonlong because I'm sure there's a better color combination that works here, your help would be much appreciated.

### CODE REVIEW

**Comment by johndbritton** [comment]
Thanks @tarebyte, this is just what I was looking for. Once we're happy with colors, feel free to :ship:

**Comment by jasonlong** [comment]
What do you think about using our brand blue (`#4183c4`) and white text? The massaged the green value here (`#58D984`) for better contrast.

screen shot 2016-01-07 at 3 34 46 pm

**Comment by johndbritton** [comment]
Works for me, but the text alignment on the left side seems a bit off.

**Comment by jasonlong** [comment]
Ha, you're right. I just threw this together in Sketch real quick. If you guys are :thumbsup: @tarebyte can just update the CSS here.

**Comment by tarebyte** [comment]
:+1: thanks @jasonlong!

**Comment by tarebyte** [comment]
screen shot 2016-01-07 at 3 54 47 pm

**Comment by johndbritton** [comment]
:shipit:

**Comment by johndbritton** [comment]
Set `MOTD` to `<strong>Tell your story.</strong> We're seeking stories from instructors using Classroom for GitHub. <a href="http://bit.ly/1K0cDQx">Share yours</a>.`

Looks good:

screen shot 2016-01-07 at 9 10 00 pm

**Pull request merged**
