### PR TITLE
Add Flipper to Classroom

### PR DESCRIPTION
**Pull request by tarebyte**
Since we have new features that we are planning to work on, it may be a good idea to have some feature flipping :dolphin: 

### Task List
- [x] Add Flipper and connect it to Redis
- [x] Add Flipper route to stafftools
- [x] Make staff group for features
- [x] Give models the ability to have a `flipper_id`
~~Build Flipper into our own UI?~~

The :art: 

screen shot 2016-02-28 at 9 48 21 pm

screen shot 2016-02-28 at 9 48 31 pm

Right now we are just using the default flipper ui, I would like to build this into our own UI.

But I think that is out of the scope of this PR, thoughts?

/cc @johndbritton

### CODE REVIEW

**Comment by tarebyte** [comment]
@johndbritton I've deployed it to prod so you can get a feel for what it looks like.

**Comment by johndbritton** [comment]
Looks good to me.

> Build Flipper into our own UI?

The `flipper-ui` gem looks really nice, is there a way to add our stafftools chrome to that? If not, maybe a way to link back to stafftools from the flipper ui?

**Comment by johndbritton** [comment]
@tarebyte Integrating this into the stafftools UI isn't a giant issue, we could treat this like Sidekiq and host it at `/stafftools/flipper`.

**Comment by tarebyte** [comment]
@johndbritton that's where I set it up to be :grin: https://github.com/education/classroom/pull/474/files#diff-21497849d8f00507c9c8dcaf6288b136R47

So I think this is good to :ship: :dash:

**Comment by johndbritton** [comment]
:shipit:

**Pull request merged**
