### PR TITLE
Redesign Dashboard with Search

### PR DESCRIPTION
**Pull request by srinjoym**
Working on a new design for the Classroom dashboard! After running the beta test for multiple classrooms per org, we saw a definite need for teachers to be able to sort through their classrooms in the dashboard.

This design adds a new search bar to quickly sort through classrooms and also presents each classroom in it's own card. Still prototyping on the design to feel free to give feedback!

screencapture-localhost-5000-classrooms-2019-04-03-09_32_56

### CODE REVIEW

**Comment by BenEmdon** [comment]
This looks awesome! Cant wait!

**Comment by brandonrosage** [comment]
@srinjoym I pushed up some broad style and layout changes that remove a lot of unnecessary CSS (in favor of Primer utility classes) and polish the responsive layout. Help me make sure I got all the use cases covered 👍

**Comment by srinjoym** [comment]
Just pushed up some final tweaks for rendering the latest assignments for an organization. @mozzadrella I think we're ready for a beta test/launch, should we come up with a release plan?

**Comment by mozzadrella** [comment]
This looks *amazing.* 
Let's ship it and let @ericdrosado know when it's merged and he can notify the Campus Advisors and we can collect any feedback via Issues in the repo.

**Comment by srinjoym** [comment]
Deployed 🚢

**Pull request merged**
