### PR TITLE
Install bullet

### PR DESCRIPTION
**Pull request by mkcode**
Install and configures bullet: https://github.com/flyerhzm/bullet

This will find N+1 queries, Unused Eager loading, and needed counter caches.

This configures bullet in a strict way, where bullet will raise errors in test mode. This will prevent any N+1 (and more) queries from being merged into master.

/cc @johndbritton

### CODE REVIEW

**Comment by mkcode** [comment]
Initial run errors:

```
  1) GroupAssignmentsController POST #create does not allow groupings to be added that do not belong to the organization
     Failure/Error: Unable to find matching line from backtrace
     Bullet::Notification::UnoptimizedQueryError:
       user: chris
       N+1 Query detected
         Organization => [:users]
         Add to your finder: :includes => [:users]
       N+1 Query method call stack
         /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:43:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

       /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:43:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:14:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

  2) GroupAssignmentsController GET #edit returns success status and sets the group assignment
     Failure/Error: Unable to find matching line from backtrace
     Bullet::Notification::UnoptimizedQueryError:
       user: chris
       N+1 Query detected
         Organization => [:users]
         Add to your finder: :includes => [:users]
       N+1 Query method call stack
         /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:10:in `block (2 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:61:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

       /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:10:in `block (2 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:61:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:14:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

  3) GroupAssignmentsController DELETE #destroy sets the `deleted_at` column for the group assignment
     Failure/Error: Unable to find matching line from backtrace
     Bullet::Notification::UnoptimizedQueryError:
       user: chris
       N+1 Query detected
         Organization => [:users]
         Add to your finder: :includes => [:users]
       N+1 Query method call stack
         /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:10:in `block (2 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:80:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

       /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:10:in `block (2 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:80:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:14:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

  4) GroupAssignmentsController DELETE #destroy redirects back to the organization
     Failure/Error: Unable to find matching line from backtrace
     Bullet::Notification::UnoptimizedQueryError:
       user: chris
       N+1 Query detected
         Organization => [:users]
         Add to your finder: :includes => [:users]
       N+1 Query method call stack
         /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:10:in `block (2 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:98:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

       /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:10:in `block (2 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:98:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:14:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

  5) GroupAssignmentsController DELETE #destroy calls the DestroyResource background job
     Failure/Error: Unable to find matching line from backtrace
     Bullet::Notification::UnoptimizedQueryError:
       user: chris
       N+1 Query detected
         Organization => [:users]
         Add to your finder: :includes => [:users]
       N+1 Query method call stack
         /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:10:in `block (2 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:90:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

       /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:10:in `block (2 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:90:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:14:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

  6) GroupAssignmentsController PATCH #update correctly updates the assignment
     Failure/Error: Unable to find matching line from backtrace
     Bullet::Notification::UnoptimizedQueryError:
       user: chris
       N+1 Query detected
         Organization => [:users]
         Add to your finder: :includes => [:users]
       N+1 Query method call stack
         /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:10:in `block (2 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:71:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

       /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:10:in `block (2 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:71:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:14:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

  7) GroupAssignmentsController GET #show returns success status
     Failure/Error: Unable to find matching line from backtrace
     Bullet::Notification::UnoptimizedQueryError:
       user: chris
       N+1 Query detected
         Organization => [:users]
         Add to your finder: :includes => [:users]
       N+1 Query method call stack
         /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:10:in `block (2 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:54:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

       /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:10:in `block (2 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/controllers/group_assignments_controller_spec.rb:54:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:14:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

  8) GroupAssignmentInvitationsController GET #show unauthenticated request redirects the new user to sign in with GitHub
     Failure/Error: Unable to find matching line from backtrace
     Bullet::Notification::UnoptimizedQueryError:
       user: chris
       N+1 Query detected
         Organization => [:users]
         Add to your finder: :includes => [:users]
       N+1 Query method call stack
         /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/controllers/group_assignment_invitations_controller_spec.rb:5:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/controllers/group_assignment_invitations_controller_spec.rb:9:in `block (4 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

       /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/controllers/group_assignment_invitations_controller_spec.rb:5:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/controllers/group_assignment_invitations_controller_spec.rb:9:in `block (4 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:14:in `block (2 levels) in <top (required)>'
     # ./spec/support/bullet.rb:9:in `block (2 levels) in <top (required)>'

  9) GroupAssignmentInvitation#to_param should return the key
     Failure/Error: Unable to find matching line from backtrace
     Bullet::Notification::UnoptimizedQueryError:
       user: chris
       N+1 Query detected
         Organization => [:users]
         Add to your finder: :includes => [:users]
       N+1 Query method call stack
         /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/models/group_assignment_invitation_spec.rb:46:in `block (3 levels) in <top (required)>'
         /Users/chris/src/projects/github/classroom/spec/models/group_assignment_invitation_spec.rb:49:in `block (3 levels) in <top (required)>'

       /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/models/group_assignment_invitation_spec.rb:46:in `block (3 levels) in <top (required)>'
       /Users/chris/src/projects/github/classroom/spec/models/group_assignment_invitation_spec.rb:49:in `block (3 levels) in <top (required)>'
     # ./spec/support/bullet.rb:14:in `block (2 levels) in <top (required)>'

  10) GroupAssignmentInvitation#title returns the group assignments title
      Failure/Error: Unable to find matching line from backtrace
      Bullet::Notification::UnoptimizedQueryError:
        user: chris
        N+1 Query detected
          Organization => [:users]
          Add to your finder: :includes => [:users]
        N+1 Query method call stack
          /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
          /Users/chris/src/projects/github/classroom/spec/models/group_assignment_invitation_spec.rb:37:in `block (3 levels) in <top (required)>'
          /Users/chris/src/projects/github/classroom/spec/models/group_assignment_invitation_spec.rb:40:in `block (3 levels) in <top (required)>'

        /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
        /Users/chris/src/projects/github/classroom/spec/models/group_assignment_invitation_spec.rb:37:in `block (3 levels) in <top (required)>'
        /Users/chris/src/projects/github/classroom/spec/models/group_assignment_invitation_spec.rb:40:in `block (3 levels) in <top (required)>'
      # ./spec/support/bullet.rb:14:in `block (2 levels) in <top (required)>'

  11) Organization#all_assignments with Assignments and GroupAssignments should return an array of Assignments and GroupAssignments
      Failure/Error: Unable to find matching line from backtrace
      Bullet::Notification::UnoptimizedQueryError:
        user: chris
        N+1 Query detected
          Organization => [:assignments]
          Add to your finder: :includes => [:assignments]
        N+1 Query method call stack
          /Users/chris/src/projects/github/classroom/app/models/organization.rb:21:in `all_assignments'
          /Users/chris/src/projects/github/classroom/spec/models/organization_spec.rb:37:in `block (4 levels) in <top (required)>'

        /Users/chris/src/projects/github/classroom/app/models/organization.rb:21:in `all_assignments'
        /Users/chris/src/projects/github/classroom/spec/models/organization_spec.rb:37:in `block (4 levels) in <top (required)>'
      # ./spec/support/bullet.rb:14:in `block (2 levels) in <top (required)>'

  12) GroupAssignment when the title is updated updates the slug
      Failure/Error: Unable to find matching line from backtrace
      Bullet::Notification::UnoptimizedQueryError:
        user: chris
        N+1 Query detected
          Organization => [:users]
          Add to your finder: :includes => [:users]
        N+1 Query method call stack
          /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
          /Users/chris/src/projects/github/classroom/spec/models/group_assignment_spec.rb:5:in `block (3 levels) in <top (required)>'
          /Users/chris/src/projects/github/classroom/spec/models/group_assignment_spec.rb:8:in `block (3 levels) in <top (required)>'

        /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
        /Users/chris/src/projects/github/classroom/spec/models/group_assignment_spec.rb:5:in `block (3 levels) in <top (required)>'
        /Users/chris/src/projects/github/classroom/spec/models/group_assignment_spec.rb:8:in `block (3 levels) in <top (required)>'
      # ./spec/support/bullet.rb:14:in `block (2 levels) in <top (required)>'

  13) GroupAssignment#public? returns true if Assignments public_repo column is true
      Failure/Error: Unable to find matching line from backtrace
      Bullet::Notification::UnoptimizedQueryError:
        user: chris
        N+1 Query detected
          Organization => [:users]
          Add to your finder: :includes => [:users]
        N+1 Query method call stack
          /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
          /Users/chris/src/projects/github/classroom/spec/models/group_assignment_spec.rb:36:in `block (3 levels) in <top (required)>'

        /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
        /Users/chris/src/projects/github/classroom/spec/models/group_assignment_spec.rb:36:in `block (3 levels) in <top (required)>'
      # ./spec/support/bullet.rb:14:in `block (2 levels) in <top (required)>'

  14) GroupAssignment#private? returns false if Assignments public_repo column is true
      Failure/Error: Unable to find matching line from backtrace
      Bullet::Notification::UnoptimizedQueryError:
        user: chris
        N+1 Query detected
          Organization => [:users]
          Add to your finder: :includes => [:users]
        N+1 Query method call stack
          /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
          /Users/chris/src/projects/github/classroom/spec/models/group_assignment_spec.rb:43:in `block (3 levels) in <top (required)>'

        /Users/chris/src/projects/github/classroom/spec/factories/group_assignment.rb:6:in `block (3 levels) in <top (required)>'
        /Users/chris/src/projects/github/classroom/spec/models/group_assignment_spec.rb:43:in `block (3 levels) in <top (required)>'
      # ./spec/support/bullet.rb:14:in `block (2 levels) in <top (required)>'

Finished in 18.28 seconds (files took 3.53 seconds to load)
131 examples, 14 failures
```

**Comment by mkcode** [comment]
Ok! All those N+1 errors were being caused from some factory girl weirdness. https://github.com/education/classroom/commit/6185f2f424782930088e07308b64ba5de79e4a73 Fixed this.

And no n+1 or other errors found in the app!

**Comment by johndbritton** [comment]
:cool:

**Comment by tarebyte** [comment]
Looks good to me as well thanks @mkcode!

**Comment by johndbritton** [comment]
@mkcode Can you merge master into your branch? Once that's done we can :ship:

**Pull request merged**
