### PR TITLE
Hide Download Repositories button when there are no assignment repos

### LINKED ISSUE #1589: Don't show download repo button unless there assignment repos
See https://github.com/education/classroom-assistant/issues/71#issuecomment-423628486 for details

### PR DESCRIPTION
**Pull request by rmacklin**
Fixes #1589

### CODE REVIEW

**Comment by johndbritton** [comment]
Thinking about this a bit more and remembering https://github.com/education/classroom-assistant/issues/71, maybe we should set the button to disabled instead of removing it when there are no repositories to download.

**Comment by BenEmdon** [comment]
I agree, I think it would be preferable to disable the button instead of removing it. Sorry for changing the constraints @rmacklin

**Comment by rmacklin** [comment]
Sorry I wasn't able to get back to this. I was aiming to do it this weekend, but you beat me to it! Thanks for fixing it :)

**Comment by BenEmdon** [comment]
Thanks for contributions, I made sure to merge them 😄

**Pull request closed without merging**
