### PR TITLE
Use Docker Compose for dependencies instead of Homebrew services

### PR DESCRIPTION
**Pull request by tarebyte**
We've had plenty of setup issues in the past such as https://github.com/education/classroom/issues/1243 and it's really difficult to know what you need in order to get classroom working since there are so many parts.

I'd like to propose that we move the project from using Homebrew services to using Docker Compose for our external dependencies.

**What does this mean?**
All it means is that instead of using brew services and pointing our app to the default ports for each respective service we turn them on using docker-compose and then point them to a custom port we have configured in `docker-compose.yml`

**How does this change my workflow?**
Hopefully it really shouldn't apart from the fact that you now need to have docker installed on your computer.

All of the files in `script` have been or will be updated to use docker-compose.

**Why not just fully containerize it**
I thought about it, and we've had Pull Requests in the past to do this. But I really didn't like how much it interfered with my development flow using things like pry or running rails commands that we had to prefix `docker-compose` on to the command.

Hopefully this is a happy medium

**What can I do to help?**
I'm glad you asked! I'd love for folks to pull this down and see if it works for them, and if not leave feedback so that I can get it working.

## TODO
- [x] Get tests working with new configuration
- [ ] Get feedback from active contributors whose workflow I would mess up 😄 
- [x] Update the README and other related documents to reflect the new world order

<br><br>
💖 **Thanks** 💖

### CODE REVIEW

**Comment by trombonekenny** [comment]
@tarebyte Did you see https://github.com/mdwheele/classroom-docker by @mdwheele ? That seemed pretty useful to me for wrapping Classroom in docker-compose. Of course, anything that changes in Classroom to support that better is even nicer!

**Comment by tarebyte** [comment]
> Did you see https://github.com/mdwheele/classroom-docker by @mdwheele ? That seemed pretty useful to me for wrapping Classroom in docker-compose. Of course, anything that changes in Classroom to support that better is even nicer!

I hadn't, that would've been nice to know when I started 😅

**Comment by tarebyte** [comment]
@Kadaaran it looks like your issue is that your node install didn't work, maybe retry install `nodejs`?

**Comment by talsafran** [comment]
Just did a fresh run of the codebase with docker and worked! 🐳

**Pull request merged**
