### PR TITLE
Use modals instead of js confirm

### LINKED ISSUE #135: "Remove this organization" improvements
The terminology used for removing an organization may be confusing:

screen shot 2015-08-25 at 3 15 24 pm

"Remove and reset organization" along with an explanation that the organization will be removed from classroom and all of the repositories, teams, and users created by the app will be removed.

Also, we might want to guard against accidental clicks by requiring a confirmation step. Check out the flow for deleting a repository on GitHub for some inspiration.

Maybe even separate out the two functions: `reset` deletes everything created by classroom, while `remove` just takes the org off of classroom's list. If you re-add a removed org, everything just comes back (since it's all still in the db maybe).

### LINKED ISSUE #180: ZeroClipboard not working with turbolinks
Just a reminder to myself

### PR DESCRIPTION
**Pull request by tarebyte**
This fixes #180 and will close #135 once we get the copy changed.

Instead of using the js confirm we'll use a confirm modal just like on github.com

Once I get the :+1: I'll go ahead and update the rest of them to this standard.

/cc @johndbritton 

delete_resource_modal

### CODE REVIEW

**Comment by johndbritton** [comment]
:+1: for style. Check the copy on GitHub. I'm pretty sure it shows the name in the modal.

**Comment by johndbritton** [comment]
You might consider using organization login as the confirmation.

**Comment by tarebyte** [comment]
I agree in using the login, it's more consistent.

**Comment by tarebyte** [comment]
@johndbritton this is good to go, I'd like one more :eyes: on the copy.

delete_resource_modal

**Comment by johndbritton** [comment]
> Are you ABSOLUTELY sure?
> Unexpected things will happen if you don't read this!
> This action CANNOT be undone. This will permanently delete all teams and repositories created with Classroom for GitHub from the @organization organization.
> Please type in the name of the organization to confirm.
> I understand the consequences, reset this organization

screen shot 2015-09-09 at 3 08 50 pm

**Comment by tarebyte** [comment]
screen shot 2015-09-09 at 10 34 39

**Comment by tarebyte** [comment]
:ship: :dash:

**Pull request merged**
