### PR TITLE
Fixed undefined behavior on re-accepting an invitation link of a deleted repo

### PR DESCRIPTION
**Pull request by hackerkid**
If a repo is deleted and the student uses the invitation link again it results in an undefined behavior. This has been fixed by showing that repo has been deleted.

### CODE REVIEW

**Comment by hackerkid** [comment]
@tarebyte Is there any problem with the PR. I can improve it if there is some issue.

**Comment by tarebyte** [comment]
Hi @hackerkid :wave: I honestly just haven't had a chance to review this yet. I should be able to look at this tomorrow.

**Comment by tarebyte** [comment]
It would also be helpful to write some tests so we know the output is what we expect it to be.

Thanks!

**Comment by hackerkid** [comment]
@tarebyte Sure.  I would update the pull request with some tests. :+1:

**Comment by hackerkid** [comment]
Closing for a better pull request :)

**Pull request closed without merging**
