### PR TITLE
Fixing a tiny typo.

### PR DESCRIPTION
**Pull request by seanhussey**
No functional changes.

### CODE REVIEW

**Comment by tarebyte** [comment]
@seanhussey thanks for the copy fix! Can you [accept the GitHub CLA](https://cla.github.com/education/accept/seanhussey) and then we can merge your Pull Request.

**Comment by tarebyte** [comment]
:pager: @seanhussey

**Comment by seanhussey** [comment]
All set!

**Comment by tarebyte** [comment]
@seanhussy would also mind merging master into your branch? I can't merge the PR without it

**Comment by seanhussey** [comment]
All set, pending Travis.

**Pull request merged**
