### PR TITLE
Sort assignments by title

### PR DESCRIPTION
**Pull request by ashleytqy**
Addresses https://github.com/education/classroom/issues/1269

Assignments are now sorted alphabetically, rather by their `updated_at` attribute. I made the change in the controller level instead of the view level because that's how it was done before. Let me know if this looks ok!

screen shot 2018-02-19 at 2 07 31 pm

### CODE REVIEW

**Comment by Kadaaran** [comment]
Travis build is failing for some reason (a deprecated spec I believe) @ashleytqy do you need a hand with this ?

**Comment by ashleytqy** [comment]
hey @Kadaaran ! not really sure how to proceed re: the failing specs, can you give me some pointers? thanks!

**Comment by Kadaaran** [comment]
@ashleytqy I merged master into your branch to see if Travis fails after a new build or not, let's wait and see if it works 🤞

**Comment by ashleytqy** [comment]
@Kadaaran Okay will do! But I'm a bit confused to why it failed because I didn't make any changes to the `GroupAssignmentInvitationsController`

**Comment by Kadaaran** [comment]
@ashleytqy Mmmh. I thought it used not directly another controller. But after reproducing what you did on my side my RSPEC are working fine. Do you mind adding some comments above or even a new line (just so there is new code to push) and then push it to see how Travis behave ? 🙏  (It might be random but I want to check if this is the same spec that are failing 🤔)

**Comment by ashleytqy** [comment]
@Kadaaran same spec failing 😢

**Pull request merged**
